import React from 'react';
import { 
  Box, Typography, Paper, Table, TableBody, TableCell, 
  TableContainer, TableHead, TableRow, Chip 
} from '@mui/material';
import { 
  LineChart, Line, BarChart, Bar, ResponsiveContainer, 
  XAxis, YAxis, CartesianGrid, PieChart, Pie, Cell 
} from 'recharts';

const primaryBlue = '#002B5C';
const secondaryYellow = '#FFD700';

const lineData = [
  { n: 'Jan', v: 20 }, { n: 'Feb', v: 100 }, { n: 'Mar', v: 80 },
  { n: 'Apr', v: 140 }, { n: 'May', v: 120 }, { n: 'Jun', v: 150 }, { n: 'Jul', v: 200 }
];

const barData = [
  { n: 'Jan', v: 40 }, { n: 'Feb', v: 60 }, { n: 'Mar', v: 45 },
  { n: 'Apr', v: 80 }, { n: 'May', v: 55 }, { n: 'Jun', v: 90 }, { n: 'Jul', v: 70 }
];

const pieData = [{ v: 400 }, { v: 300 }, { v: 300 }];
const COLORS = [primaryBlue, secondaryYellow, '#1E40AF'];

const Reports = () => {
  return (
    <Box sx={{ display: 'flex', gap: 3, mt: 2 }}>
      {/* CHAP TOMON - DETAILED REPORTS */}
      <Box sx={{ flex: 3 }}>
        <Paper elevation={0} sx={{ p: 4, borderRadius: '30px' }}>
          <Typography variant="h6" sx={{ fontWeight: 800 }}>Detailed Enrollment</Typography>
          <Typography variant="caption" sx={{ color: '#64748B', mb: 3, display: 'block' }}>
            Performance overview placemd list
          </Typography>

          <TableContainer sx={{ border: '1px solid #F1F5F9', borderRadius: '15px', mb: 4 }}>
            <Table>
              <TableHead sx={{ bgcolor: '#F8FAFC' }}>
                <TableRow>
                  {['Report ID', 'Report Name', 'Generated By', 'Subject', 'Date', 'Status'].map((h) => (
                    <TableCell key={h} sx={{ fontWeight: 800, py: 1.5 }}>{h}</TableCell>
                  ))}
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell>ST0011</TableCell>
                  <TableCell>
                    <ResponsiveContainer width={150} height={60}>
                      <LineChart data={lineData}><Line type="monotone" dataKey="v" stroke={primaryBlue} strokeWidth={2} dot={false} /></LineChart>
                    </ResponsiveContainer>
                  </TableCell>
                  <TableCell>
                    <ResponsiveContainer width={100} height={60}>
                      <BarChart data={barData}><Bar dataKey="v" fill={primaryBlue} radius={[2, 2, 0, 0]} /></BarChart>
                    </ResponsiveContainer>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>IELTS Adv.</Typography>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>White A</Typography>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>Level B</Typography>
                  </TableCell>
                  <TableCell sx={{ color: '#64748B' }}>15/02/2026</TableCell>
                  <TableCell>
                    <Chip label="Active" size="small" sx={{ bgcolor: '#DCFCE7', color: '#166534', fontWeight: 700, mb: 0.5, display: 'flex' }} />
                    <Chip label="Active" size="small" sx={{ bgcolor: '#DCFCE7', color: '#166534', fontWeight: 700, mb: 0.5, display: 'flex' }} />
                    <Chip label="Inactive" size="small" sx={{ bgcolor: '#FEE2E2', color: '#991B1B', fontWeight: 700, display: 'flex' }} />
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>

          <Typography variant="h6" sx={{ fontWeight: 800, mb: 2 }}>Reports list</Typography>
          <TableContainer sx={{ border: '1px solid #F1F5F9', borderRadius: '15px' }}>
            <Table>
              <TableBody>
                {[
                  { id: 'ST0011', name: 'Report Enrollment', chart: 'enroll' },
                  { id: 'ST0012', name: 'Courses analytics', chart: 'course' },
                  { id: 'ST0013', name: 'Courses analytics', chart: 'course' },
                  { id: 'ST0014', name: 'Report Evelogs', chart: 'enroll' },
                ].map((row, i) => (
                  <TableRow key={i}>
                    <TableCell sx={{ fontWeight: 600 }}>{row.id}</TableCell>
                    <TableCell sx={{ fontWeight: 600 }}>{row.name}</TableCell>
                    <TableCell>
                       <ResponsiveContainer width={120} height={40}>
                         <BarChart data={barData}><Bar dataKey="v" fill={i % 2 === 0 ? primaryBlue : secondaryYellow} /></BarChart>
                       </ResponsiveContainer>
                    </TableCell>
                    <TableCell sx={{ color: '#64748B' }}>Coraching</TableCell>
                    <TableCell sx={{ color: '#64748B' }}>15/02/2026</TableCell>
                    <TableCell>
                      <Chip label={i % 2 === 0 ? "Active" : "Inactive"} size="small" sx={{ fontWeight: 700, bgcolor: i % 2 === 0 ? '#DCFCE7' : '#FEE2E2', color: i % 2 === 0 ? '#166534' : '#991B1B' }} />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </Paper>
      </Box>

      {/* O'NG TOMON - ANALYTICS LIST */}
      <Box sx={{ flex: 1.2, display: 'flex', flexDirection: 'column', gap: 3 }}>
        <Paper elevation={0} sx={{ p: 3, borderRadius: '25px' }}>
          <Typography sx={{ fontWeight: 800 }}>Courses analytics list</Typography>
          <Typography variant="caption" sx={{ color: '#64748B', mb: 2, display: 'block' }}>Diverses analytics list</Typography>
          <ResponsiveContainer width="100%" height={120}>
            <BarChart data={barData}><Bar dataKey="v" fill={primaryBlue} radius={[4, 4, 0, 0]} /></BarChart>
          </ResponsiveContainer>
          <Box sx={{ display: 'flex', gap: 2, mt: 2 }}>
            <PieChart width={80} height={80}><Pie data={pieData} innerRadius={20} outerRadius={35} dataKey="v">{pieData.map((_, i) => <Cell key={i} fill={COLORS[i]} />)}</Pie></PieChart>
            <PieChart width={80} height={80}><Pie data={pieData} innerRadius={20} outerRadius={35} dataKey="v">{pieData.map((_, i) => <Cell key={i} fill={COLORS[i]} />)}</Pie></PieChart>
          </Box>
        </Paper>

        <Paper elevation={0} sx={{ p: 3, borderRadius: '25px' }}>
          <Typography sx={{ fontWeight: 800, mb: 2 }}>Complex analytical chart</Typography>
          <ResponsiveContainer width="100%" height={150}>
            <LineChart data={lineData}>
               <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#F1F5F9" />
               <Line type="monotone" dataKey="v" stroke={primaryBlue} strokeWidth={3} dot={false} />
            </LineChart>
          </ResponsiveContainer>
          <Box sx={{ mt: 2 }}>
             {['IELTS Adv.', 'Level Ad', 'Level B'].map((item, i) => (
               <Box key={i} sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.5 }}>
                 <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: COLORS[i] }} />
                 <Typography variant="caption" sx={{ fontWeight: 600 }}>{item}</Typography>
               </Box>
             ))}
          </Box>
        </Paper>
      </Box>
    </Box>
  );
};

export default Reports;